apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  type: LoadBalancer # Expose le service en externe
  ports:
  - port: 8000
    targetPort: 5000
  selector:
    app: gateway
