apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  type: ClusterIP
  ports:
  - name: plaintext
    port: 9092
    targetPort: 9092
  - name: plaintext-internal
    port: 29092
    targetPort: 29092
  selector:
    app: kafka
