name: Flask Microservices CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Install dependencies and run testss
      - name: Install dependencies and run tests
        run: |
          services=("reservation" "user" "salle")
          for service in "${services[@]}"; do
            echo "Running tests for $service"
            cd $service
            pip install -r requirements.txt
            pip install pytest  # Installe pytest
            pytest tests || exit 1
            cd ..
          done
  build-and-push:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Build and Push Docker images for all services
      - name: Build and Push Docker Images
        run: |
          services=("reservation" "user" "salle" "gatWay")
          docker login -u oumayoungbuin -p Eriroha1924wsv
          for service in "${services[@]}"; do
            echo "Building and pushing image for $service"
            docker build -t oumayoungbuin/flask_reservation_project:$service ./$service
            docker push oumayoungbuin/flask_reservation_project:$service
          done

  deploy:
    runs-on: ubuntu-latest
    needs: [build-and-push, tests]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      # Installer Minikube
      - name: Install Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          chmod +x minikube-linux-amd64
          sudo mv minikube-linux-amd64 /usr/local/bin/minikube
          minikube version
          minikube start --driver=docker
  
      # Installer kubectl
      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/v1.26.3/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl
          kubectl version --client
  
      - name: Configure kubectl for Minikube
        run: |
          mkdir -p $HOME/.kube
          echo "$(minikube kubectl -- config view)" > $HOME/.kube/config
          kubectl cluster-info

      - name: Deploy with kubectl
        run: |
          kubectl apply -f ./k8s
  
      # Afficher les services déployés
      - name: Show services
        run: kubectl get svc
